# Generated by Django 3.1 on 2020-09-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('creado', models.DateField(auto_now_add=True)),
                ('editado', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escaneos',
            fields=[
                ('id_Escaneos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('lugar', models.CharField(max_length=55)),
                ('celular', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id_local', models.AutoField(primary_key=True, serialize=False)),
                ('nombreComercial', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=180)),
                ('srcLogo', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('direccion', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('like', models.IntegerField()),
                ('estrella', models.IntegerField()),
                ('vistas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_Permiso', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=180)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
    ]
